### ISSUE TITLE
Use stable_baselines3 instead of old version

### ISSUE THREAD

**Issue by galleon** [ashishrana160796/prototyping-self-driving-agents#1]
Stable Baseline is now in maintenance mode as indicated [here](https://stable-baselines.readthedocs.io/en/master/)

Stable Baselines3 (SB3) is the next major version of Stable Baselines. It is based on PyTorch.

For the user of this repo, the benefit of using SB3 would be an easier installation process since it works on a default collab notebook. No need to downgrade anything.

API is the same, so just the import need to be changed:
```from stable_baselines3 import HER, SAC, DDPG```

If ok I could push a PR

**Comment by ashishrana160796** [comment]
Hi @galleon, thanks for the help regarding this issue. And sorry for keep you waiting on this, got occupied with something else.

Please, go ahead and push a replacement for this in `milestone-two` directory. Replacing content of `her_sac_baseline_agent_parking_task.ipynb`. Thanks again!!

**Comment by ashishrana160796** [comment]
closed with raised PR #2. thanks!!
